//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 PE_tools.rc 使用
//
#define IDC_MYICON                      2
#define IDD_PETOOLS_DIALOG              102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDI_PETOOLS                     107
#define IDI_SMALL                       108
#define IDC_PETOOLS                     109
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_MAIN                 129
#define IDD_DIALOG_PE                   132
#define IDD_DIALOG_QUDUAN               133
#define IDD_DIALOG1                     134
#define IDD_DIALOG_DATAMULU             134
#define IDD_DIALOG_SUBSYTEM_INFO        136
#define IDD_DIALOG_TIME_TO_RILI         137
#define IDD_DIALOG_IMPORT               139
#define IDD_DIALOG_TEZHNEG              149
#define IDC_BUTTON_PE                   1000
#define IDC_BUTTON_ABOUT                1001
#define IDC_BUTTON_EXIT                 1002
#define IDC_LIST_MOUDLE                 1006
#define IDC_LIST_PROCESS                1007
#define IDC_STATIC1                     1009
#define IDC_STATIC2                     1010
#define IDC_STATIC_PE                   1019
#define IDC_BUTTON_PE_EXIT              1020
#define IDC_BUTTON_SECTION              1021
#define IDC_BUTTON_MULU                 1022
#define IDC_STATIC_ENCRYPTION           1023
#define IDC_STATIC_IMAGEBASE            1024
#define IDC_STATIC_IMAGESIZE            1025
#define IDC_STATIC_CODEBASE             1026
#define IDC_STATIC_DATABASE             1027
#define IDC_STATIC_SEALIGNMET           1028
#define IDC_STATIC_FILEALIGNMET         1029
#define IDC_STATIC_ISFLAG               1030
#define IDC_EDIT_ENCRYPTION             1036
#define IDC_EDIT_IMAGESIZE              1037
#define IDC_EDIT_CODEBASE               1038
#define IDC_EDIT_DATABASE               1039
#define IDC_EDIT_SEALIGNMET             1040
#define IDC_EDIT_FILEALIGNMET           1041
#define IDC_EDIT_ISFLAG                 1042
#define IDC_EDIT_IMAGEBASE              1043
#define IDC_EDIT_ZIXITONG               1044
#define IDC_EDIT_SECTIONNUMBER          1045
#define IDC_EDIT_TIME                   1046
#define IDC_EDIT_PESIZE                 1047
#define IDC_EDIT_TEZHNEG                1048
#define IDC_EDIT_JIAOYANHE              1049
#define IDC_EDIT_PEHEADER               1050
#define IDC_EDIT19                      1051
#define IDC_EDIT_MULU                   1051
#define IDC_STATIC_ZIXITONG             1052
#define IDC_LIST_QUDUAN                 1055
#define IDC_EDIT_SECTOPM_NUMBER         1056
#define IDC_BUTTON_SECTION_SAVE         1057
#define IDC_BUTTON_SECTION_F5           1058
#define IDC_BUTTON_SECTION_EXIT         1059
#define IDC_EDIT_EXPORT_RVA             1060
#define IDC_EDIT_IMPORT_RVA             1061
#define IDC_EDIT_SRECOR_RVA             1062
#define IDC_EDIT_TRY_RVA                1063
#define IDC_EDIT_ANQUAN_RVA             1064
#define IDC_EDI_CHONG_RVA               1065
#define IDC_EDIT_CHONG_RVA              1065
#define IDC_EDI_DEBUG_RVA               1066
#define IDC_EDIT_DEBUG_RVA              1066
#define IDC_EDIT_BAN_RVA                1067
#define IDC_EDIT_POINTRE_RVA            1068
#define IDC_EDIT_TLS_RVA                1069
#define IDC_EDIT_JIA_RVA                1070
#define IDC_EDIT_BANGDING_RVA           1071
#define IDC_EDIT_IAT_RVA                1072
#define IDC_EDIT_YANCHI_RVA             1073
#define IDC_EDIT_COM_RVA                1074
#define IDC_EDIT_BAOLIU_RVA             1075
#define IDC_EDIT_EXPORT_SIZE            1076
#define IDC_EDIT_IMPORT_SIZE            1077
#define IDC_EDIT_SRECOR_SIZE            1078
#define IDC_EDIT_TRY_SIZE               1079
#define IDC_EDIT__ANQUAN_SIZE           1080
#define IDC_EDIT_ANQUAN_SIZE            1080
#define IDC_EDIT_CHONG_SIZE             1081
#define IDC_EDIT_DEBUG_SZIE             1082
#define IDC_EDIT_BAN_SIZE               1083
#define IDC_EDIT_POINTRE_SIZE           1084
#define IDC_EDIT_TLS_SIZE               1085
#define IDC_EDIT_JIA_SIZE               1086
#define IDC_EDIT_BANGDING_SIZE          1087
#define IDC_EDIT_IAT_SIZE               1088
#define IDC_EDIT_YANCHI_SIZE            1089
#define IDC_EDIT_COM_SIZE               1090
#define IDC_EDIT34                      1091
#define IDC_EDIT_BAOLIU_SIZE            1091
#define IDC_BUTTON1                     1092
#define IDC_BUTTON_EXPORT_INFO          1092
#define IDC_BUTTON_IMPORT_EXIT          1092
#define IDC_BUTTON2                     1093
#define IDC_BUTTON_IMPORT_INFO          1093
#define IDC_BUTTON_UPP                  1093
#define IDC_BUTTON3                     1094
#define IDC_BUTTON_RESOURCE_INFO        1094
#define IDC_BUTTON4                     1095
#define IDC_BUTTON5                     1096
#define IDC_BUTTON6                     1097
#define IDC_BUTTON7                     1098
#define IDC_BUTTON8                     1099
#define IDC_BUTTON9                     1100
#define IDC_BUTTON10                    1101
#define IDC_BUTTON11                    1102
#define IDC_BUTTON_ZIXITONG_INFO        1102
#define IDC_BUTTON_TIME_INFO            1103
#define IDC_BUTTON_TEZHENG_INFO         1104
#define IDC_RADIO2                      1108
#define IDC_RADIO3                      1109
#define IDC_RADIO4                      1110
#define IDC_RADIO5                      1111
#define IDC_RADIO6                      1112
#define IDC_RADIO7                      1113
#define IDC_RADIO8                      1114
#define IDC_RADIO9                      1115
#define IDC_RADIO10                     1116
#define IDC_RADIO11                     1117
#define IDC_RADIO12                     1118
#define IDC_RADIO13                     1119
#define IDC_RADIO14                     1120
#define IDC_BUTTON_SUBSYTEM_OK          1121
#define IDC_BUTTON_SUBSYTEM_EXIT        1122
#define IDC_STATIC_SUBSYTEM_NUM         1123
#define IDC_STATIC_SECTION_NUMBER       1124
#define IDC_EDIT1                       1126
#define IDC_DATETIMEPICKER1             1127
#define IDC_DATETIMEPICKER2             1128
#define IDC_BUTTON_TIME_EXIT            1129
#define IDC_BUTTON_TIME_OK              1130
#define IDC_BUTTON_TIME_NOW             1131
#define IDC_BUTTON_TIME_JISUAN          1132
#define IDC_LIST_IMPORT_LI              1133
#define IDC_LIST_IMPORT_INFO            1134
#define IDC_STATIC_IMPORT_NUMBER        1136
#define IDC_STATIC_THUNK_NUMBER         1137
#define IDC_CHECK1                      1146
#define IDC_CHECK2                      1147
#define IDC_CHECK3                      1148
#define IDC_CHECK4                      1149
#define IDC_CHECK5                      1150
#define IDC_CHECK6                      1151
#define IDC_CHECK7                      1152
#define IDC_CHECK8                      1153
#define IDC_CHECK9                      1154
#define IDC_CHECK10                     1155
#define IDC_CHECK11                     1156
#define IDC_CHECK12                     1157
#define IDC_CHECK13                     1158
#define IDC_CHECK14                     1159
#define IDC_CHECK15                     1160
#define IDM_TIME                        32781
#define IDM_RILI                        32782
#define IDM_FOV                         32783
#define IDM_FIND                        32784
#define IDM_OPEN                        32785
#define ID_32786                        32786
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        150
#define _APS_NEXT_COMMAND_VALUE         32787
#define _APS_NEXT_CONTROL_VALUE         1147
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
